version: '3.8'

services:
  yocto-builder:
    build:
      context: .  # Uses the Dockerfile in the same directory
      args:
        USER_UID: ${UID:-1000}  # Matches host user's UID (Linux/Mac)
        USER_GID: ${GID:-1000}
    image: yocto-dev-oni # Name of the built image
    container_name: yocto-build-env-oni
    stdin_open: true  # -i (interactive)
    tty: true         # -t (pseudo-TTY)
    volumes:
      - ${ROOT_DIR}:/home/Oni/yocto/ # Persistent build dir
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile 
        - action: rebuild
          path: ./docker-compose.yml
    user: Oni  # Run as non-root
    working_dir: /home/Oni/yocto/
    command: ["/usr/bin/dumb-init", "--", "/bin/bash"]  # Proper init system
